package ssa_test

import (
	"testing"

	"bitbucket.org/openbankingteam/conformance-dcr/pkg/ssa"
)

const PubKeyTest = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzSkSfBX6BqUU2xOLKH6M
E5R3ZEPi7Ab7fXCRGUibKVpzVfC/+ldIuFkmbmpnrtCgEGMmeZK2DdcHt/PTk+6R
R5Jn7Huhxtn4tjLqe4Rle53QGIfdIwQyZAgKvNa9rjrQ5no2Ux2ViSu0csS0FaHg
2RK06JGBBwk1HZShDRxQpwuoW7fwPmhybpzZGypM4LsHGIzKrW2ygYI/1u5zDeFJ
Lj8qr7Qvkny4z/X3Na+mkgsQ8z/smDyBG6ZRRpMzFriFN+F+scq6nUGDYSuQ4RSm
R95fGAKyibC6uuAN3bcWbIEtuLTTPr9mPMJv0YZLPQ/ItC8gyMdK9MMSqRzbtP/V
4QIDAQAB
-----END PUBLIC KEY-----`

func TestValidateSSA(t *testing.T) {
	ssaJwt := `eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzI1NiJ9.eyJpc3MiOiJPcGVuQmFua2luZyBMdGQiLCJpYXQiOjE0OTI3NTYzMzEsImV4cCI6MTU5NTc1NzU1MCwiYXVkIjoiT3BlbkJhbmtpbmcgVFBQIFVuaXF1ZSBJRCIsInN1YiI6Ik9wZW5CYW5raW5nIFRQUCBTb2Z0d2FyZSBVbmlxdWUgSUQiLCJjbGllbnRfbmFtZSI6IkFtYXpvbiBQcmltZSBMdGQiLCJjbGllbnRfdXJpIjoiaHR0cHM6Ly9wcmltZS5hbWF6b24uY29tIiwidHBwX3NvZnR3YXJlX2lkIjoiT3BlbkJhbmtpbmcgVFBQIFNvZnR3YXJlIFVuaXF1ZSBJRCIsInRwcF9zb2Z0d2FyZV9yb2xlcyI6WyJQSVNQIiwiQUlTUCJdLCJ0cHBfcm9sZXMiOlsiUElTUCIsIkFJU1AiLCJQSUlTUCJdLCJ0cHBfaWQiOiJPcGVuQmFua2luZyBUUFAgVW5pcXVlIElEIiwidHBwX25hbWUiOiJPcGVuQmFua2luZyBUUFAgUmVnaXN0ZXJlZCBOYW1lIiwidHBwX2NvbXBldGVudF9hdXRob3JpdHkiOiJPcGVuQmFua2luZyBUUFAgUmVnaXN0ZXJlZCBDb21wZXRlbnQgQXV0aG9yaXR5IiwidHBwX2NvbXBldGVudF9hdXRob3JpdHlfaWQiOiJPcGVuQmFua2luZyBUUFAgUmVnaXN0ZXJlZCBBdXRob3JpdHkgSUQiLCJ0cHBfcHRjX25hbWUiOiJPcGVuQmFua2luZyBUUFAgUmVnaXN0ZXJlZCBQcmltYXJ5IFRlY2huaWNhbCBDb250YWN0IE5hbWUiLCJ0cHBfcHRjX2VtYWlsIjoiT3BlbkJhbmtpbmcgVFBQIFJlZ2lzdGVyZWQgUHJpbWFyeSBUZWNobmljYWwgQ29udGFjdCBFbWFpbCIsInRwcF9qd2tzX2VuZHBvaW50IjoiaHR0cHM6Ly9qd2tzLm9wZW5iYW5raW5nLm9yZy51ay90cHBfaWQuamt3cyJ9.khx6q_2i5YcK18wnugRK_YG_04XB1f4oP5yXao0OkqLvrPIeco01lmedm1Ly67kX1H3F1PU7tt_r9DZ5AZKTRYH3rBw62KD_WXt4uRirC83Z6ut5ViqZECgQ_jjrVDAHAsWgnt_gnk26WAzvuAGe1cYfpy_zpw-B-41nfLoC9LyHowRxq0qK3Z0QkkgWTLqiXxflvjRkA_xX4GwEUpx0hGK_tRsEYxoXZ14mojYM8wcQJ5VWpsvYysmNjQ0B420l9ZVyAHRrCbdLh7yviB3t3sMtReWwM8X49aKumCkgO8zyaxaCV2_hbkVpuZ1CBO7L-0ruypT62ymTDqsY64ZBxw`
	ssaValidator := ssa.NewSSAValidator(ssa.PublicKeyLookupFromByteSlice([]byte(PubKeyTest)))
	ssaValue, err := ssaValidator.Validate(ssaJwt)
	if err != nil {
		t.Errorf("should not expect error. Got %s", err.Error())
	}
	if ssaValue.Issuer != "OpenBanking Ltd" {
		t.Errorf("Issuer should be Open Banking Ltd. Got %#v", ssaValue.Issuer)
	}
}
